library(Seurat)
library(ggplot2)
library(ArchR)
setwd("snATAC-seq/snATAC_cortex_TSS5_Frag1000/")
atac <- readRDS("Save-ArchR-Project.rds")
ff=dir("ArrowFiles")
atac@sampleColData <- DataFrame(row.names = substr(ff,1,nchar(ff)-6), ArrowFiles = paste0('ArrowFiles/',ff))
seqlevels(atac@peakSet)<- sub('chr','MFA',seqlevels(atac@peakSet))
atac=addMotifAnnotations(ArchRProj = atac, motifSet = "JASPAR2020", name = "Motif")
saveRDS(atac, "Save-ArchR-Project.rds")
