require(EBImage)
im = readImage('/home/wangqi9/Pictures/newplot.png')
im = channel(im,"gray")
im = medianFilter(im, size=7)
thr <- im > otsu(im)
writeImage(thr,file='/home/wangqi9/Pictures/ddd.jpg')

require(EBImage)
df=read.table(gzfile("matrix1.mtx.gz"))
m=sparseMatrix(i = df$V1, j = df$V2, x = df$V3)
im=Image(as.matrix(m))
im = medianFilter(im, size=7)
thr <- im > otsu(im)
writeMM(as(imageData(thr),"dgCMatrix"), "matrix.mtx")
m=readMM("matrix.mtx")
im=Image(as.matrix(m))
plot(im)

