options(stringsAsFactors = FALSE)
x=read.table('out_filename_Stats.txt',as.is=T,sep='\t')
x=tail(x,10)
df=do.call(rbind,strsplit(substr(x$V1,1,nchar(x$V1)-4),'_'))
x=cbind(df,x)
x[,1]=as.integer(x[,1])
x[,2]=as.integer(x[,2])
df=read.table(text=do.call(rbind,strsplit(substr(x$V3,2,nchar(x$V3)-1),'_')))
x=cbind(x[,1:2],df)
xl=c(-1,5)
yl=c(-1,5)
cl=gplots::colorpanel(10,'white','red')
x[,3:6]=round(10*x[,3:6])+1
p=function(d,cl,tt) plot(d,pch=22,bg=cl,cex=6,main=tt, xlim=xl, ylim=yl, xaxt='n', yaxt='n', xlab='', ylab='')
pdf('s.pdf',height=7,width=6.5)
par(mfrow=c(2,2))
p(x[,1:2], cl[x$V1], 'background')
p(x[,1:2], cl[x$V2], 'normal')
p(x[,1:2], cl[x$V3], 'LUAD')
p(x[,1:2], cl[x$V4], 'LUSC')
dev.off()

